export declare function mqttParse(topic: string): string[];
export declare function wampUriParse(topic: string): string[];
export declare function defaultParse(topic: string): string[];
export declare function restoreUri(topic: string[]): string;
export declare function restoreMqttUri(topic: string[]): string;
export declare function mqttMatch(topic: string, filter: string): boolean;
export declare function wampMatch(topic: string, filter: string): boolean;
export declare function isPattern(topicParts: string[]): boolean;
export declare function match(topicParts: string[], filterParts: string[]): boolean;
export declare function intersect(topicParts: string[], filterParts: string[]): boolean;
export declare function merge(topicParts: string[], patternParts: string[]): string[];
export declare function extract(topicParts: string[], patternParts: string[]): string[];
export declare function mqttExtract(topic: string, pattern: string): string[] | null;
